---
function:
  handler: src/movement/index.handler
  name: omni-pb-rt-stop-db-stream-${self:provider.stage}
  description: OMNI PB Real Time Stop Table Stream Process - ${self:provider.stage}
  runtime: nodejs18.x
  layers:
    - {Ref: NodeModulesLambdaLayer}
  timeout: 600
  package:
    patterns:
      - '!**/*'
      - 'src/stop/index.js'
      - 'src/shared/dynamo.js'
 
  events:
      - stream:
          arn: arn:aws:dynamodb:us-east-1:332281781429:table/omni-pb-rt-stop-dev/stream/2024-05-09T20:02:58.575
          batchSize: 1
          maximumRetryAttempts: 3

  environment:
    MOVEMENT_DB: 'omni-pb-rt-movement-dev'

