---
function:
  handler: src/stop/index.handler
  name: ${self:service}-stop-table-stream-${self:provider.stage}
  description: OMNI PB Real Time Stop Table Stream Process - ${self:provider.stage}

  layers:
    - { Ref: NodeModulesLambdaLayer }
  timeout: 300
  tags:
    Name: ${self:service}-stop-table-stream-${self:provider.stage}
  package:
    patterns:
      - '!**/*'
      - 'src/stop/index.js'
      - 'src/shared/*'

  events:
    - sqs:
        arn: ${ssm:/omni-pb-wt/${self:provider.stage}/stop-table-stream-queue-arn}
        batchSize: 1

  environment:
    MOVEMENT_DB: ${ssm:/omni-pb-rt/${self:provider.stage}/movement/db}
    ORDERS_TABLE_NAME: ${ssm:/omni-pb-rt/${self:provider.stage}/orders/db}
    MOVEMENT_ORDER_TABLE_NAME: ${ssm:/omni-pb-rt/${self:provider.stage}/movement-order/db}
    MOVEMENT_TABLE_NAME: ${ssm:/omni-pb-rt/${self:provider.stage}/movement/db}
    ADD_MILESTONE_TABLE_NAME: ${ssm:/omni-pb-wt/${self:provider.stage}/milestones-update/db}
    ORDER_STATUS_TABLE_NAME: ${ssm:/omni-204-create-shipment/${self:provider.stage}/status/ddb.name}
    CONSOL_STATUS_TABLE_NAME: ${ssm:/omni-live-204/${self:provider.stage}/consol-status/ddb.tableName}
    GET_ORDERS_API_ENDPOINT: ${ssm:/omni-204-create-shipment/${self:provider.stage}/get-orders.url}
    AUTH: ${ssm:/omni-204-create-shipment/${self:provider.stage}/apis.auth}
    CHECK_POD_API_ENDPOINT: ${ssm:/omni-lvlp/${self:provider.stage}/loadtracking/url}
    MOVEMENT_ORDER_INDEX_NAME: ${ssm:/omni-pb-rt/${self:provider.stage}/movement-order/ddb.index}
    MOVEMENT_ORIGIN_INDEX_NAME: ${ssm:/omni-pb-rt/${self:provider.stage}/movement-originstopIndex/ddb.index}
    MOVEMENT_DESTINATION_INDEX_NAME: ${ssm:/omni-pb-rt/${self:provider.stage}/movement-deststop/ddb.index}
    STOP_TABLE_NAME: ${ssm:/omni-pb-rt/${self:provider.stage}/stop/db}
    STOP_INDEX_NAME: ${ssm:/omni-pb-rt/${self:provider.stage}/stop/ddb.index}
    STOP_STREAM_QUEUE_URL: ${ssm:/omni-pb-wt/${self:provider.stage}/stop-table-stream-queue-url}
    ENVIRONMENT: ${self:provider.stage}
