---
function:
  handler: src/movement/index.handler
  name: omni-pb-rt-movement-stream-${self:provider.stage}
  description: OMNI PB Real Time Movement Stream Process - ${self:provider.stage}
  runtime: nodejs18.x
  layers:
    - {Ref: NodeModulesLambdaLayer}
  timeout: 600
  package:
    patterns:
      - '!**/*'
      - 'src/movement/index.js'
      - 'src/shared/dynamo.js'
 
  events:
      - stream:
          arn: ${ssm:/omni-pb-rt/${self:provider.stage}/movement/ddb.streamArn}
          batchSize: 1
          maximumRetryAttempts: 3

  environment:
    ERROR_SNS_TOPIC_ARN: ${ssm:/omni-pb-rt/${self:provider.stage}/error-notification/arn}
    ENVIRONMENT: ${self:provider.stage}
    ORDERS_TABLE_NAME: ${ssm:/omni-pb-rt/${self:provider.stage}/orders/db}
    MOVEMENT_ORDER_TABLE_NAME: ${ssm:/omni-pb-rt/${self:provider.stage}/movement-order/db}
    MOVEMENT_TABLE_NAME: ${ssm:/omni-pb-rt/${self:provider.stage}/movement/db}
    ADD_MILESTONE_TABLE_NAME: ${ssm:/omni-pb-214/${self:provider.stage}/add-milestone/db}
